### ISSUE TITLE
斗胆请教一下，这个是什么原因导致的呢？

### ISSUE THREAD

**Issue by CCjinqiu** [sanshanya/hoshino_xcw#11]
Traceback (most recent call last):
  File "run.py", line 1, in <module>
    import hoshino
  File "C:\Users\Administrator\Desktop\XCWrobot\Hoshino\hoshino\__init__.py", line 17, in <module>
    from hoshino.typing import CQEvent, Message, Union
  File "C:\Users\Administrator\Desktop\XCWrobot\Hoshino\hoshino\typing.py", line 8, in <module>
    from . import HoshinoBot
ImportError: cannot import name 'HoshinoBot' from partially initialized module 'hoshino' (most likely due to a circular
import) (C:\Users\Administrator\Desktop\XCWrobot\Hoshino\hoshino\__init__.py)

**Comment by Noelloe** [comment]
一样的问题。。。

**Comment by CCjinqiu** [comment]
> 一样的问题。。。

我回退到上一版本的_init_.py文件后就正常了，别的不用动
